### ISSUE TITLE
Questions about PAL free-time-slot and FTL latency

### ISSUE THREAD

**Issue by shuangchenli** [SimpleSSD/SimpleSSD#1]
First of all, I would like to thank all the authors for the contribution to the community!
I have been reading through the code and learnt a lot. I have a few questions. I would really appreciate it if I can get the answers here.

(1) I had a hard time understanding the variable "ChFreeSlots" and "DieFreeSlots". I guess a bit comments on what each of the element representing in "std::map<uint64_t, std::map<uint64_t, uint64_t>* >" would help me out. Also, I am confused by the initialization code with timing constants in  line 60-100, "PAL.cc" file. A little bit explanation would be great.

(2) I am just curious, does the latency of the in-SSD controller running the FTL algorithm modeled? If yes, could you please point me to that code? If no, may I learn from you how much this latency usually is, so that you guys decided to ignore it? 

(3) I am also looking forward the update for in-SSD DRAM modeling, which is mentioned as your future work in the CAL paper. I am wondering what impact the in-SSD DRAM would bring to results of the current simulator? Does the in-SSD DRAM work as a "cache" for pages? 

Thanks in advance!

**Comment by SimpleSSD** [comment]
Hi, shuangchenli,

Sorry for late response, the email notification was turn off on this repo.

1) You may want to check [here](http://simplessd.yonsei.ac.kr/details.html#parallelism-abstraction-layer-pal) for more details about Parallelism Abstraction Layer.
And for codes, I will ask who developed that part.

2) The latency model for FTL is not added on current version of SimpleSSD.
This is one of our future works.

3) Yes, in-SSD DRAM works as a cache of I/O requests.
Performance impacts:
 The write performance will be enhanced if write-back cache exists.
 The overall performance may enhanced (depends on I/O pattern).

More questions are welcome.

Thanks.
