### ISSUE TITLE
The simpleSSD does not support page cached operation of nand flash?

### ISSUE THREAD

**Issue by shengwenliang** [SimpleSSD/SimpleSSD#1]
Hi, when I read the simple SSD project, I find the simpleSSD project only has page read, page write and page erase operation. The simpleSSD project does not include the page cached command. So, in the further version, the project will support this command?
Thanks

**Comment by kukdh1** [comment]
Hi, shengwenLeong

Yes, currently PAL of SimpleSSD only supports read, write and erase operations.
I plan to support more advanced commands such as copyback and cached commands.

Thanks.
