### ISSUE TITLE
Question about DMAFunction 

### ISSUE THREAD

**Issue by ray5273** [SimpleSSD/SimpleSSD#3]
Hello,

I have a question what is role of  DMAFunction dowrite/doread HIL::read/write function in hil/hil.cc file . 

I know this function is related to I/O,

But I don't know what is role of this dmafunction in this HIL::read/write function?

does this function directly read/write something in memory or cpu?

Thank you.

**Comment by kukdh1** [comment]
Hi,

The DMA function is used to copy data from host/SSD to SSD/host.
 - DMA Read: Copy data in host DRAM to SSD's local DRAM
 - DMA Write: Copy data in SSD's local DRAM to host DRAM

For example, if host sends I/O request using NVMe protocol, kernel driver fills the submission queue (SQ) entry with proper request data (64bytes).
As the SQ is stored in host DRAM, SSD need to read SQ entry (64bytes) from the host DRAM.
SSD calculates the physical address of SQ entry using SQ base address (configured when SQ creation) and doorbell register and perform DMA read operation to get SQ entry.

Also, SSD need to read data from host DRAM when perform write I/O operation (reads the data should be written to SSD) and write data to host DRAM when perform read I/O operation (writes the data should be read from SSD).

Thanks.
