### ISSUE TITLE
latency 

### ISSUE THREAD

**Issue by sac2019** [SimpleSSD/SimpleSSD#5]
hi,

1- I wonder which initial parameters have been set in the configuration file or in the code file which may be used in the calculation of the delay in SimpleSSD? and which parameters make the difference between min, average and max latency? ( only these parameters LSB, CSB, MSB ?)
2- Is there any exact formula for calculating the latency?

thanks

**Comment by sac2019** [comment]
hi,
I run a trace with only one read request on simple ssd, when changing the  "LSBRead = 400000000" parameter, the latency didn't change!? always  : 28954
why it is always remain the same value?!!!

Morover, when I change this parameter EnableReadCache = 1==>0  the results is changed to  21664

when running two read request the latency are:
min=22599,  max=

why the min latency is less than when I just run on request!??
is any other parameter should be changed to provide different timing for read?

**Comment by kukdh1** [comment]
Hi,

Please provide your SSD configuration for SimpleSSD and SimpleSSD-Standalone (or FullSystem).
Latency calculation of NAND flash array cannot represented in single equation -- please see SimpleSSD paper in IEEE CAL.

Thanks.

**Comment by sac2019** [comment]
Hi, 
I use this version 
SimpleSSD Standalone v2.0

when I change the 
LSBwrite
I could see the change in result (by increasing this parameter the latency also increases in output file) but changing the same parameter for read, the result always remain the same.

**Comment by kukdh1** [comment]
I cannot help you if you don't provide configuration file (I cannot reproduce your problem).
Please attach two files (*.cfg) and open this issue again.

**Comment by sac2019** [comment]
[sample-trace2.cfg.txt](https://github.com/SimpleSSD/SimpleSSD/files/5585362/sample-trace2.cfg.txt)
[sample-trace2-nocache.cfg.txt](https://github.com/SimpleSSD/SimpleSSD/files/5585363/sample-trace2-nocache.cfg.txt)
 I run a trace with one line (a read request with size 4K)
change the LSBRead = 750000, 7500000, 75000000
but always the results remain same!
avg_latency=28.95 (with cache)
avg latency =21.7 (without cache)

**Comment by kukdh1** [comment]
Hi,

Please change the `[ftl]FillRatio` to `1.0`.
If FTL does not contains mapping for requested logical address, it returns immediately.

Thanks.
